### ISSUE TITLE
Wiring diagram 

### ISSUE THREAD

**Issue by WouterJN** [ootjersb/pislave#2]
Thank you again Ben for the great work with this project.

Are you sure that the wiring diagram is correct? When I measure the DC voltage between Pin 3 (green/white) and Pin 5 (blue/white) of the RJ45 connector on my ITHO WPU I measure 16V instead of the 5v that I'm expecting.

**Comment by ootjersb** [comment]
Sorry, late response; I think I missed this issue, not sure why I did not get notified. Fixed the issue with the wiring diagram. The pin 5 can be left disconnected, which is now displayed in the diagram as well.
